### ISSUE TITLE
使用 `hexo g` 生成静态文件时出现  TypeError: Cannot set property 'lastIndex' of undefined

### ISSUE THREAD

**Issue by wangming1993** [wangming1993/wangming1993.github.com#1]
使用 `hexo g` 生成静态文件时出现:

```
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
TypeError: Cannot set property 'lastIndex' of undefined
    at highlight (/Users/mike/workspace/github/wangming1993.github.com/node_modules/highlight.js/lib/highlight.js:511:35)
    at /Users/mike/workspace/github/wangming1993.github.com/node_modules/highlight.js/lib/highlight.js:561:21
    at Array.forEach (native)
    at Object.highlightAuto (/Users/mike/workspace/github/wangming1993.github.com/node_modules/highlight.js/lib/highlight.js:560:40)
    at /Users/mike/workspace/github/wangming1993.github.com/node_modules/hexo-util/lib/highlight.js:100:25
    at highlight (/Users/mike/workspace/github/wangming1993.github.com/node_modules/hexo-util/lib/highlight.js:103:7)
    at highlightUtil (/Users/mike/workspace/github/wangming1993.github.com/node_modules/hexo-util/lib/highlight.js:22:14)
    at /Users/mike/workspace/github/wangming1993.github.com/node_modules/hexo/lib/plugins/filter/before_post_render/backtick_code_block.js:49:15
    at String.replace (native)
    at Hexo.backtickCodeBlock (/Users/mike/workspace/github/wangming1993.github.com/node_modules/hexo/lib/plugins/filter/before_post_render/backtick_code_block.js:15:31)
    at Hexo.tryCatcher (/Users/mike/workspace/github/wangming1993.github.com/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.<anonymous> (/Users/mike/workspace/github/wangming1993.github.com/node_modules/bluebird/js/release/method.js:15:34)
    at /Users/mike/workspace/github/wangming1993.github.com/node_modules/hexo/lib/extend/filter.js:68:35
at tryCatcher (/Users/mike/workspace/github/wangming1993.github.com/node_modules/bluebird/js/release/util.js:16:23)
    at Object.gotValue (/Users/mike/workspace/github/wangming1993.github.com/node_modules/bluebird/js/release/reduce.js:155:18)
    at Object.gotAccum (/Users/mike/workspace/github/wangming1993.github.com/node_modules/bluebird/js/release/reduce.js:144:25)
    at Object.tryCatcher (/Users/mike/workspace/github/wangming1993.github.com/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/mike/workspace/github/wangming1993.github.com/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/mike/workspace/github/wangming1993.github.com/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromiseCtx (/Users/mike/workspace/github/wangming1993.github.com/node_modules/bluebird/js/release/promise.js:606:10)
    at Async._drainQueue (/Users/mike/workspace/github/wangming1993.github.com/node_modules/bluebird/js/release/async.js:138:12)
```

通过逐步调试，发现 markdown 写法上的错误：

```
load_factor = ht[0].used / ht[0].size
```

正确写法：

```c
load_factor = ht[0].used / ht[0].size
```

**需要明确指定语言**

**Comment by vpakati** [comment]
你是说在markdown里需要明确指明代码块所使用的语言吗？
我这边已经明确指出几个代码块使用的语言为yml了，但还是出现了这种错误。
个人感觉是highlight.js不支持渲染语言类型为yml和json的代码块，因为front-matter就是遵循json和yml语法的。
后来把该代码块的类型设置为空，就不报错了。
这是我的_config.yml
```
highlight: # Code block syntax highlight settings, powered by highlight.js
  enable: true
  line_number: true
  auto_detect: true # Enable auto-detection if no language is specified
  tab_replace: # Replace tabs by n space(s); if the value is empty, tabs won’t be replaced
```
